# Generated by Django 5.0.6 on 2024-06-04 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from Aplicaciones.Modelos.models import Usuario



class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='publicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='Modelos.publicacion'),
            preserve_default=False,
        ),
    ]
