# Generated by Django 5.0.6 on 2024-06-05 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0002_oferta_autor_oferta_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='oferta_aceptada',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacion_ofertada', to='Modelos.oferta'),
        ),
    ]
