# Generated by Django 5.0.6 on 2024-06-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0003_publicacion_oferta_aceptada'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10),
        ),
    ]
