# Generated by Django 5.0.4 on 2024-06-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0004_alter_notificacion_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ('-fecha',)},
        ),
    ]
