# Generated by Django 5.0.6 on 2024-06-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0004_oferta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('eliminada', 'Eliminada'), ('validada', 'Validada')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('eliminada', 'Eliminada'), ('validada', 'Validada')], default='pendiente', max_length=10),
        ),
    ]
