# Generated by Django 5.0.4 on 2024-06-10 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0006_alter_oferta_estado_alter_oferta_precio_estimado_and_more'),
    ]

