# Generated by Django 5.0.4 on 2024-06-10 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0006_alter_oferta_estado_alter_oferta_precio_estimado_and_more'),
    ]

# Ac hubo un problema de migiraciones. Este create model esta de mas y por eso tira error. ya esta hecho en l migracion 0001
#     operations = [
#        migrations.CreateModel(
#            name='Intercambios',
#            fields=[
#                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='aceptado', max_length=10)),
#                ('fecha_aceptacion', models.DateTimeField(null=True)),
#                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios', to='Modelos.publicacion')),
#            ],
#        ),
#    ]
