# Generated by Django 5.0.4 on 2024-06-12 00:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0007_intercambios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambios',
            name='fecha_aceptacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_publicacion', to='Modelos.publicacion'),
        ),
    ]
