# Generated by Django 5.0.4 on 2024-06-12 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0008_alter_intercambios_fecha_aceptacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambios',
            name='fecha_aceptacion',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
