# Generated by Django 5.0.6 on 2024-06-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0009_alter_intercambios_fecha_aceptacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(related_name='favoritos', to='Modelos.publicacion'),
        ),
    ]
