# Generated by Django 5.0.4 on 2024-06-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0009_alter_intercambios_fecha_aceptacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='success', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='descripcion',
            field=models.TextField(default='success'),
            preserve_default=False,
        ),
    ]
