# Generated by Django 5.0.4 on 2024-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0010_alter_message_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='foto',
            field=models.ImageField(blank=True, upload_to='archivos-estaticos/fotos_chats/'),
        ),
    ]
