# Generated by Django 5.0.6 on 2024-06-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0010_usuario_favoritos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_cuenta',
            field=models.CharField(choices=[('activo', 'Activo'), ('baneado', 'Baneado'), ('suspendido', 'Suspendido'), ('deshabilitado', 'Deshabilitado')], default='activo', max_length=15),
        ),
    ]
