# Generated by Django 5.0.4 on 2024-06-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0011_alter_message_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='foto',
            field=models.ImageField(upload_to='archivos-estaticos/fotos_chats/'),
        ),
    ]
