# Generated by Django 5.0.6 on 2024-06-23 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0010_notificacion_tipo_alter_notificacion_descripcion'),
        ('Modelos', '0011_delete_persona_usuario_estado_cuenta'),
    ]

    operations = [
    ]
