# Generated by Django 5.0.4 on 2024-06-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0012_merge_20240623_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('eliminada', 'Eliminada')], default='pendiente', max_length=10),
        ),
    ]
