# Generated by Django 5.0.4 on 2024-06-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0012_alter_message_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='unread_messages',
            field=models.BooleanField(default=False),
        ),
    ]
