# Generated by Django 5.0.6 on 2024-06-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0013_alter_publicacion_estado'),
        ('Modelos', '0013_historial'),
    ]

    operations = [
    ]
