# Generated by Django 5.0.4 on 2024-06-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0014_merge_0013_alter_publicacion_estado_0013_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='motivo_de_baja',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
