# Generated by Django 5.0.4 on 2024-06-26 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0014_merge_0013_alter_publicacion_estado_0013_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechas', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FotoPublicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='publicidad_fotos/')),
                ('publicidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='Modelos.publicidad')),
            ],
        ),
    ]
