# Generated by Django 5.0.4 on 2024-06-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0014_alter_usuario_is_superuser'),
        ('Modelos', '0014_merge_0013_alter_publicacion_estado_0013_historial'),
    ]

    operations = [
    ]
