# Generated by Django 5.0.4 on 2024-06-30 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0015_merge_20240626_1649'),
        ('Modelos', '0015_usuario_motivo_de_baja'),
    ]

    operations = [
    ]
