# Generated by Django 5.0.4 on 2024-06-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0015_publicidad_fotopublicidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotopublicidad',
            name='foto',
        ),
        migrations.AddField(
            model_name='fotopublicidad',
            name='imagen',
            field=models.ImageField(default='archivos-estaticos/fotos_publicaciones/velero1.jpeg', upload_to='publicidades'),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='contenido',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='titulo',
            field=models.CharField(default='nuevo', max_length=100),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='fechas',
            field=models.JSONField(default=list),
        ),
    ]
