# Generated by Django 5.0.4 on 2024-06-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0016_merge_20240630_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('eliminada', 'Eliminada')], default='pendiente', max_length=10),
        ),
    ]
