# Generated by Django 5.0.4 on 2024-06-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0016_remove_fotopublicidad_foto_fotopublicidad_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotopublicidad',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='titulo',
        ),
        migrations.AddField(
            model_name='fotopublicidad',
            name='foto',
            field=models.ImageField(blank=True, default='archivos-estaticos/fotos_publicaciones/velero1.jpeg', null=True, upload_to='publicidades'),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='estado',
            field=models.CharField(default='activo', max_length=10),
        ),
    ]
