# Generated by Django 5.0.4 on 2024-07-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0017_alter_oferta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('eliminada', 'Eliminada')], default='aceptado', max_length=10),
        ),
    ]
