# Generated by Django 5.0.4 on 2024-07-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0017_alter_oferta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('eliminada', 'Eliminada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=10),
        ),
    ]
