# Generated by Django 5.0.4 on 2024-06-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0017_remove_fotopublicidad_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicidad',
            old_name='fechas',
            new_name='fecha',
        ),
    ]
