# Generated by Django 5.0.4 on 2024-07-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0019_intercambios_calificacion_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambios',
            name='descripcion_comprador',
            field=models.TextField(blank=True),
        ),
    ]
