# Generated by Django 5.0.4 on 2024-07-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0020_intercambios_descripcion_comprador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambios',
            name='descripcion_autor',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='intercambios',
            name='descripcion_comprador',
            field=models.TextField(null=True),
        ),
    ]
