# Generated by Django 5.0.4 on 2024-06-30 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0021_alter_publicidad_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotopublicidad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='archivos-estativos/publicidades/'),
        ),
        migrations.AlterField(
            model_name='fotopublicidad',
            name='publicidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='Modelos.publicidad'),
        ),
    ]
