# Generated by Django 5.0.4 on 2024-06-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0023_alter_fotopublicidad_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicidad',
            name='estado',
        ),
        migrations.AddField(
            model_name='publicidad',
            name='cliente',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
