# Generated by Django 5.0.4 on 2024-06-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0024_remove_publicidad_estado_publicidad_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='foto_central',
            field=models.ImageField(blank=True, null=True, upload_to='archivos-estaticos/publicidades/'),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='foto_lateral',
            field=models.ImageField(blank=True, null=True, upload_to='archivos-estaticos/publicidades/'),
        ),
        migrations.DeleteModel(
            name='FotoPublicidad',
        ),
    ]
