# Generated by Django 5.0.4 on 2024-07-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0019_alter_room_estado'),
        ('Modelos', '0025_publicidad_foto_central_publicidad_foto_lateral_and_more'),
    ]

    operations = [
    ]
