# Generated by Django 5.0.4 on 2024-07-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0026_merge_20240701_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidad',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
