# Generated by Django 5.0.4 on 2024-07-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0027_alter_publicidad_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidad',
            name='fecha',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
