# Generated by Django 5.0.4 on 2024-07-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0029_alter_publicidad_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('eliminada', 'Eliminada')], default='activa', max_length=10),
        ),
    ]
