# Generated by Django 5.0.6 on 2024-07-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0021_alter_intercambios_descripcion_autor_and_more'),
        ('Modelos', '0030_publicidad_estado'),
    ]

    operations = [
    ]
