# Generated by Django 5.0.6 on 2024-07-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0031_merge_20240703_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin descripción', max_length=150, null=True),
        ),
    ]
