# Generated by Django 5.0.4 on 2024-05-21 21:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('precio_minimo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo_embarcacion', models.CharField(choices=[('barco', 'Barco'), ('velero', 'Velero'), ('yate', 'Yate'), ('lancha', 'Lancha'), ('jetski/moto de agua', 'Jetski/Moto de Agua'), ('regata', 'Regata'), ('kayac/canoa', 'Kayac/Canoa'), ('catamaran', 'Catamaran'), ('de pesca', 'De pesca'), ('superyate', 'Superyate'), ('otro', 'Otro')], max_length=60)),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='archivos-estaticos/fotos_publicaciones/')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='RealizarPublicacion.publicacion')),
            ],
        ),
    ]
