# Generated by Django 5.0.6 on 2024-06-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealizarPublicacion', '0002_publicacion_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.DeleteModel(
            name='FotoPublicacion',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
