# Generated by Django 5.0.6 on 2024-05-19 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealizarPublicacion', '0002_remove_publicacion_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='anio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='precio_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
