# Generated by Django 5.0.4 on 2024-06-02 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealizarPublicacion', '0003_estado_rename_autor_publicacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='RealizarPublicacion.estado'),
            preserve_default=False,
        ),
    ]
