# Generated by Django 5.0.4 on 2024-06-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealizarOferta', '0004_remove_oferta_autor_remove_oferta_publicacion_and_more'),
        ('RealizarPublicacion', '0003_publicacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.DeleteModel(
            name='FotoPublicacion',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
