# Generated by Django 5.0.6 on 2024-05-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealizarPublicacion', '0004_fotopublicacion_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotopublicacion',
            name='titulo',
        ),
    ]
