# Generated by Django 5.0.6 on 2024-05-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealizarPublicacion', '0005_remove_fotopublicacion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotopublicacion',
            name='foto',
            field=models.ImageField(upload_to='static/fotos_publicaciones/'),
        ),
    ]
