# Generated by Django 5.0.6 on 2024-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealizarPublicacion', '0006_alter_fotopublicacion_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotopublicacion',
            name='foto',
            field=models.ImageField(upload_to='fotos_publicaciones/'),
        ),
    ]
