# Generated by Django 5.0.4 on 2024-05-22 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealizarPublicacion', '0008_alter_fotopublicacion_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fotopublicacion',
            name='foto',
            field=models.ImageField(upload_to='archivos-estaticos/fotos_publicaciones/'),
        ),
    ]
