# Generated by Django 5.0.4 on 2024-06-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealizarOferta', '0001_initial'),
        ('RealizarPublicacion', '0003_publicacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotooferta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='archivos-estaticos/fotos_ofertas/'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacion', to='RealizarPublicacion.publicacion'),
        ),
    ]
