# Generated by Django 5.0.4 on 2024-06-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealizarOferta', '0002_alter_fotooferta_foto_alter_oferta_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='estado',
            field=models.CharField(default='pendiente', max_length=10),
        ),
    ]
