# Generated by Django 5.0.4 on 2024-06-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealizarOferta', '0003_oferta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='publicacion',
        ),
        migrations.DeleteModel(
            name='FotoOferta',
        ),
        migrations.DeleteModel(
            name='Oferta',
        ),
    ]
