# Generated by Django 5.0.6 on 2024-06-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IniciarSesion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
